# This tutorial is composed of one DAG
# Please see the DAG section of the documentation for more details:
# https://173tech.github.io/sayn/dags/

# presets are used to create standard tasks which can be used to define tasks quickly
presets:
  modelling:
    type: autosql
    file_name: '{{task.name}}.sql'
    materialisation: table
    destination:
      tmp_schema: main
      schema: main
      table: '{{user_prefix}}{{task.name}}'
    parents:
      - load_data

# DAGs define at minimum a set of tasks
# Those will be run for this DAG when SAYN runs
# To run the tutorial, run the command 'sayn run' from the project folder's root
tasks:
  # python
  # here we define a Python task
  # python tasks are stored into the python folder
  # this task loads some data into our SQLite database
  load_data:
    type: python
    class: load_data.LoadData

  # autosql
  # autosql tasks enable to write a SELECT statement and SAYN creates the table / view automatically
  # the SQL queries for those models are stored into the sql folder
  dim_tournaments:
    preset: modelling

  dim_arenas:
    preset: modelling

  dim_fighters:
    preset: modelling

  f_battles:
    preset: modelling
    parents:
      - dim_tournaments
      - dim_arenas
      - dim_fighters

  f_fighter_results:
    preset: modelling
    parents:
      - f_battles

  f_rankings:
    preset: modelling
    materialisation: view
    parents:
      - f_fighter_results
